### ISSUE TITLE
macOS python function highlight problem.

### ISSUE THREAD

**Issue by danche354** [danilo-augusto/vim-afterglow#6] opened 2018-12-04 09:56 UTC
***macOS highlight function like following***
* backgound is strange
* the itanlic font is not working
![image](https://user-images.githubusercontent.com/11846497/49433772-b7eef200-f7ed-11e8-882a-c64377a88035.png)

***On linux***
it works fine like this
![image](https://user-images.githubusercontent.com/11846497/49433834-d0f7a300-f7ed-11e8-9629-a35bad017d0e.png)

The afterglow and vimrc is the same.

**Comment by jmcken8** [comment] 2018-12-07 20:30
VIM highlights italic text when italics aren't supported by your terminal emulator.
You'll have to do something like this:

http://weibeld.net/terminals-and-shells/italics.html

And use a font that supports italics.

**Comment by danilo-augusto** [comment] 2018-12-08 00:04
I think @jmcken8 is right. It's probably an issue concerning your terminal emulator restrictions, or simply its configurations by default.

I personally use MacOS and it works well as you can see in the screenshot below. I use however the [**iTerm**](https://www.iterm2.com) application, not the default MacOS terminal.

I don't know which one you use, but I cannot reproduce the problem unless you specify further details. Because of this I'm closing this issue, but feel free to reopen it if the problem persists and its cause is in an incompatibility between this plugin and some environment *that supports italics*.

<img width="990" alt="screen shot 2018-12-08 at 00 56 28" src="https://user-images.githubusercontent.com/8104631/49678367-29e06900-fa84-11e8-93f0-50dee6dd64f7.png">

I'm also uploading a screenshot of the configurations used to enable italics in the iTerm emulator, which I cannot recommend enough! :)

<img width="918" alt="screen shot 2018-12-08 at 00 55 00" src="https://user-images.githubusercontent.com/8104631/49678370-2cdb5980-fa84-11e8-9afb-d2d81e4b4816.png">

Thanks for your feedback.

**Closed as completed by danilo-augusto** 2018-12-08 00:04 UTC

**Comment by danilo-augusto** [comment] 2018-12-08 00:08
Also, @jmcken8 answer is more complete in the sense it cites the need of a font supporting italics.
That's important too. :)

**Comment by cyrus-and** [comment] 2020-07-01 10:05
What if I just want to disable italic altogether and avoid that inverse video effect in the OP screenshot? The solution provided by @jmcken8 works but I'd rather use the iTerm default reported terminal type...

**Comment by danilo-augusto** [comment] 2020-07-01 20:50
@cyrus-and You are right! I just added an option to disable italics completely: `let g:afterglow_use_italics=0 (default: 1)`.

**Comment by cyrus-and** [comment] 2020-07-01 20:56
@danilo-augusto Awesome, thanks for the super quick action!

FYI some other themes [use](https://stackoverflow.com/questions/5486882/completely-disable-italic-text-in-gvim) the naming `let g:<theme>_<style> = 0` I don't know if this is some kind of standard...

**Comment by danilo-augusto** [comment] 2020-07-01 21:06
No problem. ;)

Thanks for the feedback!
Well there is really no standard in vim plugins hahaha

This might be something we could address, but with no canonical reference we just end up with multiple naming styles, each one claiming to follow some standard.

Personally I think it's more important to have it documented (I added it to the README in the same commit) than standardized, since the available options are rarely the same across plugins, but this is my personal take on it.

**Comment by cyrus-and** [comment] 2020-07-01 21:09
> Well there is really no standard in vim plugins hahaha

I feared that :P

> Personally I think it's more important to have it documented (I added it to the README in the same commit) than standardized

Totally agree!
