### ISSUE TITLE
Seems like tail HTML tags aren't properly highlighted in JSX files? 

### ISSUE THREAD

**Issue by ghost** [danilo-augusto/vim-afterglow#2] opened 2017-04-25 23:55 UTC
Love this colorscheme. After turning it on, though, this is what I see while editing some jsx:

![image](https://cloud.githubusercontent.com/assets/4985608/25412457/b3865932-29d7-11e7-83a1-6a0229085854.png)

Notice that the closing HTML tags are all colored like text content. By comparison, with Afterglow off, this is what I see:

![image](https://cloud.githubusercontent.com/assets/4985608/25412523/0b47fe78-29d8-11e7-99c2-6e84900884b1.png)

I'm not sure why this is happening, but since the only thing I changed between those two screenshots was commenting out `colorscheme afterglow` in my vimrc, I think it's the theme.

**Comment by frescoraja** [comment] 2018-12-08 02:56
@ssonicblue I know it's been a while and perhaps the plugin owner fixed this because I see no cause for it in the current color definitions.. but I saw an issue almost just like this appear recently after installing another plugin/colorscheme.. [oceanic-next](https://github.com/mhartington/oceanic-next) - which adds a custom syntax group called `xmlTagN` that matches a sequence like `</...>` .. and then colorizes the text inside the brackets white. my guess is that you have another color scheme or syntax highlighting plugin that causes the issue. best luck 

PS:
you can check the syntax groups highlights applied to any word by moving your cursor to any letter on the word, then inputing the following command:
`:echo join(map(synstack(line('.'),col('.')), 'synIDattr(synIDtrans(v:val), "name")'), ', ')`
this will output all the syntax groups that apply to the current word.. 
then type next command:
`:hi GroupName` where "GroupName" was the last one in the list from previous command if more than one printed

**Comment by danilo-augusto** [comment] 2018-12-09 02:07
It's been a while since this issue was posted. Well, I have been busy... 😅
And I could not reproduce this problem: it works just fine with JSX for me.
However, I should warn about possible unwanted interactions with other plugins.
"vim-javascript" changes the colors of JS files a lot, for example.
There's "vim-es6", there is "rainbow" for colorizing matching brackets/parenthesis and so on.
But sadly I cannot reproduce this bug without further details, so I'm closing the issue for now.
Please re-open if this is still a problem (even if it was a long time ago) and if the cause lies on the color scheme itself, or at least if you can provide further details.
Thanks.

**Closed as completed by danilo-augusto** 2018-12-09 02:07 UTC
